### ISSUE TITLE
Update for v6.0 Transfer

### ISSUE THREAD

**Issue by prestwich** [Storj/storj.js#1] opened 2016-12-13 00:16 UTC
Websockets are so 2016. Get with the hip HTTP transfer.

See docs here: http://storj.github.io/core/tutorial-data-transfer.html

**Comment by prestwich** [comment] 2016-12-13 00:17
Need discussion re: using `storj-lib`, ES6, etc.

**Comment by retrohacker** [comment] 2016-12-13 01:07
So my thoughts are that eventually we can support a majority of `storj-lib` in browser, so it makes sense to bring that in as a dep.

The challenge is two fold:
1) Size: Without minification, the bundle is about 1.8M as it stands right now. That will probably grow a bit. With gzip and minification, I could see it as low as 512kb. That is still pretty heavy for a dependency.
2) ES6: Assuming we only do it for the browser, we should be able to transpile back to ES5 for proper support. This would let us ship two bundles `storj.es6.js` and `storj.es5.js`. When you `require('storj-js')` server-side you would get non-transpiled code.

**Comment by retrohacker** [comment] 2016-12-29 18:06
From https://github.com/cpollard1001/storj.js/issues/1#issuecomment-268840205

Thanks @faddat! I agree re: HTTP for the first pass. The problem is HTTPS, farmers will need to issue certs and we will need to resolve to domain names to get around browser security. This also ties farmer availability to DNS resolution and brings up the question of NAT traversal strategies (and tunneling) for farmer's HTTPS endpoints. HTTP is incredibly straightforward (I have an example working now minus the OPTIONS endpoint), but HTTPS adds a layer of complexity that I'm not quite sure we want to take on.

What I'm working on today is a SIPS proposal for Contract that includes the protocols the shards need to be served over for the contract to be considered valid. This will allow us to propose new protocols for different target platforms and let farmers adopt them as desired, essentially letting the market decide. From there, we can talk through our options for the browser protocol.

As of now, I'm thinking the initial alpha of storj.js will be HTTP only. Other protocols will be implemented pending a larger project we are kicking off the beginning of next year to make some changes to core. Those changes will make plugging in new protocols unobtrusive, perhaps even pushing protocol implementation out into userspace.

**Comment by faddat** [comment] 2017-01-06 10:36
That's what I'd do if I were in your shoes:  

Get er shipped, weather or not it's fully-polished.  (Http was good enough for a very long time, chances are good that it is still OK)

:)

**Comment by retrohacker** [comment] 2017-02-09 20:52
Closing as current library supports HTTP.

**Closed as completed by retrohacker** 2017-02-09 20:52 UTC
